# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_repo',
        ),
    ]
